const GET_RESTAURANT = "restaurant/GET_RESTAURANT";
const SET_RESTAURANT = "restaurant/SET_RESTAURANT";
const GET_RESTAURANT_FAILED = "restaurant/GET_RESTAURANT_FAILED";

const INSERT_RESTAURANT = "restaurant/INSERT_RESTAURANT";
const SET_INSERT_RESTAURANT = "restaurant/SET_INSERT_RESTAURANT";
const INSERT_RESTAURANT_FAILED = "restaurant/INSERT_RESTAURANT_FAILED";

export {
  GET_RESTAURANT,
  GET_RESTAURANT_FAILED,
  SET_RESTAURANT,
  INSERT_RESTAURANT,
  SET_INSERT_RESTAURANT,
  INSERT_RESTAURANT_FAILED,
};
