const GET_RESTAURANT = "restaurant/GET_RESTAURANT";
const SET_RESTAURANT = "restaurant/SET_RESTAURANT";
const GET_RESTAURANT_FAILED = "restaurant/GET_RESTAURANT_FAILED";

export { GET_RESTAURANT, GET_RESTAURANT_FAILED, SET_RESTAURANT };
